# =========================================================
# Dockerfile - SQL Server avec initialisation automatique
# =========================================================
FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

# Copier les scripts d'init
COPY init.sql /init.sql
COPY init-db.sh /init-db.sh
RUN chmod +x /init-db.sh

USER mssql

ENTRYPOINT ["/init-db.sh"]
